name: Deploy


on:
  push:
    branches: ["ci"]


jobs:
    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup Pages
              uses: actions/configure-pages@v2
            - name: Build
              run: build_web.sh
            - uses: taiki-e/install-action@cargo-llvm-cov
              env:
                    CARGO_LLVM_COV_TARGET_DIR="dist"
            - name: Upload coverage artifact
              uses: actions/upload-pages-artifact@v1
              with:
                  path: "dist"
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4

       check_wasm:
          name: Check wasm32
          runs-on: ubuntu-latest
          steps:
            - uses: actions/checkout@v2
            - uses: actions-rs/toolchain@v1
              with:
                profile: minimal
                toolchain: 1.72.0
                target: wasm32-unknown-unknown
                override: true
            - name: Set up cargo cache
              uses: Swatinem/rust-cache@v2
            - name: Check wasm32
              uses: actions-rs/cargo@v1
              with:
                command: check
                args: --all-features --lib --target wasm32-unknown-unknown